export const token = {
  md: {
    source: '#6750A4',
    ref: {
      palette: {
        primary: {
          /* primary */
          0: '#000000',
          10: ' #001f26',
          20: ' #003640',
          25: ' #00424e',
          30: ' #004e5c',
          35: ' #005b6b',
          40: ' #00687a',
          50: ' #008399',
          60: ' #009eb9',
          70: ' #1abbd9',
          80: ' #4cd7f6',
          90: ' #acedff',
          95: ' #d8f6ff',
          98: ' #f0fbff',
          99: ' #f8fdff',
          100: '#ffffff',
        },
        secondary: {
          0: '#000000',
          10: '#36003e',
          20: '#580065',
          25: '#690079',
          30: '#7c008e',
          35: '#8f00a4',
          40: '#a200ba',
          50: '#c32cda',
          60: '#e14ef6',
          70: '#f27dff',
          80: '#fbabff',
          90: '#ffd6fd',
          95: '#ffebfb',
          98: '#fff7fa',
          99: '#fffbff',
          100: '#ffffff',
        },
        tertiary: {
          0: '#000000',
          10: '#23005c',
          20: '#3c0091',
          25: '#4900ad',
          30: '#5516be',
          35: '#612aca',
          40: '#6d3bd7',
          50: '#8758f2',
          60: '#a078ff',
          70: '#b89bff',
          80: '#d0bcff',
          90: '#e9ddff',
          95: '#f6edff',
          98: '#fef7ff',
          99: '#fffbff',
          100: '#ffffff',
        },
        error: {
          0: '#000000',
          10: '#410002',
          20: '#690005',
          25: '#7e0007',
          30: '#93000a',
          35: '#a80710',
          40: '#ba1a1a',
          50: '#de3730',
          60: '#ff5449',
          70: '#ff897d',
          80: '#ffb4ab',
          90: '#ffdad6',
          95: '#ffedea',
          98: '#fff8f7',
          99: '#fffbff',
          100: '#ffffff',
        },
        neutral: {
          0: '#000000',
          10: '#1C1B1F',
          20: '#313033',
          30: '#484649',
          40: '#605D62',
          50: '#787579',
          60: '#939094',
          70: '#AEAAAE',
          80: '#C9C5CA',
          90: '#E6E1E5',
          95: '#F4EFF4',
          99: '#FFFBFE',
          100: '#FFFFFF',
        },
        'neutral-variant': {
          0: '#000000',
          10: '#1D1A22',
          20: '#322F37',
          30: '#49454F',
          40: '#605D66',
          50: '#79747E',
          60: '#938F99',
          70: '#AEA9B4',
          80: '#CAC4D0',
          90: '#E7E0EC',
          95: '#F5EEFA',
          99: '#FFFBFE',
          100: '#FFFFFF',
        },
      },
    },
    typescale: {
      display: {
        large: {
          'font-family-name': 'Roboto',
          'font-family-style': 'Regular',
          'font-weight': '400px',
          'font-size': '57px',
          'line-height': '64px',
          'letter-spacing': '-0.25px',
        },
        medium: {
          'font-family-name': 'Roboto',
          'font-family-style': 'Regular',
          'font-weight': '400px',
          'font-size': '45px',
          'line-height': '52px',
          'letter-spacing': '0px',
        },
        small: {
          'font-family-name': 'Roboto',
          'font-family-style': 'Regular',
          'font-weight': '400px',
          'font-size': '36px',
          'line-height': '44px',
          'letter-spacing': '0px',
        },
      },
      headline: {
        large: {
          'font-family-name': 'Roboto',
          'font-family-style': 'Regular',
          'font-weight': '400px',
          'font-size': '32px',
          'line-height': '40px',
          'letter-spacing': '0px',
        },
        medium: {
          'font-family-name': 'Roboto',
          'font-family-style': 'Regular',
          'font-weight': '400px',
          'font-size': '28px',
          'line-height': '36px',
          'letter-spacing': '0px',
        },
        small: {
          'font-family-name': 'Roboto',
          'font-family-style': 'Regular',
          'font-weight': '400px',
          'font-size': '24px',
          'line-height': '32px',
          'letter-spacing': '0px',
        },
      },
      body: {
        large: {
          'font-family-name': 'Roboto',
          'font-family-style': 'Regular',
          'font-weight': '400px',
          'font-size': '16px',
          'line-height': '24px',
          'letter-spacing': '0.50px',
        },
        medium: {
          'font-family-name': 'Roboto',
          'font-family-style': 'Regular',
          'font-weight': '400px',
          'font-size': '14px',
          'line-height': '20px',
          'letter-spacing': '0.25px',
        },
        small: {
          'font-family-name': 'Roboto',
          'font-family-style': 'Regular',
          'font-weight': '400px',
          'font-size': '12px',
          'line-height': '16px',
          'letter-spacing': '0.40px',
        },
        label: {
          large: {
            'font-family-name': 'Roboto',
            'font-family-style': 'Medium',
            'font-weight': '500px',
            'font-size': '14px',
            'line-height': '20px',
            'letter-spacing': '0.10px',
          },
          medium: {
            'font-family-name': 'Roboto',
            'font-family-style': 'Medium',
            'font-weight': '500px',
            'font-size': '12px',
            'line-height': '16px',
            'letter-spacing': '0.50px',
          },
          small: {
            'font-family-name': 'Roboto',
            'font-family-style': 'Medium',
            'font-weight': '500px',
            'font-size': '11px',
            'line-height': '16px',
            'letter-spacing': '0.50px',
          },
        },
        title: {
          large: {
            'font-family-name': 'Roboto',
            'font-family-style': 'Regular',
            'font-weight': '400px',
            'font-size': '22px',
            'line-height': '28px',
            'letter-spacing': '0px',
          },
          medium: {
            'font-family-name': 'Roboto',
            'font-family-style': 'Medium',
            'font-weight': '500px',
            'font-size': '16px',
            'line-height': '24px',
            'letter-spacing': '0.15px',
          },
          small: {
            'font-family-name': 'Roboto',
            'font-family-style': 'Medium',
            'font-weight': '500px',
            'font-size': '14px',
            'line-height': '20px',
            'letter-spacing': '0.10px',
          },
        },
      },
    },
  },
};
