export const typography = {
  md: {
    sys: {
      typescale: {
        display: {
          large: {
            font: 'Roboto',
            'font-family-style': 'Regular',
            weight: '400px',
            size: '57px',
            'line-height': '64px',
            tracking: '-0.25px',
          },
          medium: {
            font: 'Roboto',
            'font-family-style': 'Regular',
            weight: '400px',
            size: '45px',
            'line-height': '52px',
            tracking: '0px',
          },
          small: {
            font: 'Roboto',
            'font-family-style': 'Regular',
            weight: '400px',
            size: '36px',
            'line-height': '44px',
            tracking: '0px',
          },
        },
        headline: {
          large: {
            font: 'Roboto',
            'font-family-style': 'Regular',
            weight: '400px',
            size: '32px',
            'line-height': '40px',
            tracking: '0px',
          },
          medium: {
            font: 'Roboto',
            'font-family-style': 'Regular',
            weight: '400px',
            size: '28px',
            'line-height': '36px',
            tracking: '0px',
          },
          small: {
            font: 'Roboto',
            'font-family-style': 'Regular',
            weight: '400px',
            size: '24px',
            'line-height': '32px',
            tracking: '0px',
          },
        },
        body: {
          large: {
            font: 'Roboto',
            'font-family-style': 'Regular',
            weight: '400px',
            size: '16px',
            'line-height': '24px',
            tracking: '0.50px',
          },
          medium: {
            font: 'Roboto',
            'font-family-style': 'Regular',
            weight: '400px',
            size: '14px',
            'line-height': '20px',
            tracking: '0.25px',
          },
          small: {
            font: 'Roboto',
            'font-family-style': 'Regular',
            weight: '400px',
            size: '12px',
            'line-height': '16px',
            tracking: '0.40px',
          },
        },
        label: {
          large: {
            font: 'Roboto',
            'font-family-style': 'Medium',
            weight: '500px',
            size: '14px',
            'line-height': '20px',
            tracking: '0.10px',
          },
          medium: {
            font: 'Roboto',
            'font-family-style': 'Medium',
            weight: '500px',
            size: '12px',
            'line-height': '16px',
            tracking: '0.50px',
          },
          small: {
            font: 'Roboto',
            'font-family-style': 'Medium',
            weight: '500px',
            size: '11px',
            'line-height': '16px',
            tracking: '0.50px',
          },
        },
        title: {
          large: {
            font: 'Roboto',
            'font-family-style': 'Regular',
            weight: '400px',
            size: '22px',
            'line-height': '28px',
            tracking: '0px',
          },
          medium: {
            font: 'Roboto',
            'font-family-style': 'Medium',
            weight: '500px',
            size: '16px',
            'line-height': '24px',
            tracking: '0.15px',
          },
          small: {
            font: 'Roboto',
            'font-family-style': 'Medium',
            weight: '500px',
            size: '14px',
            'line-height': '20px',
            tracking: '0.10px',
          },
        },
      },
    },
  },
};
